# Generated by Django 3.2 on 2022-07-06 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premier',
            field=models.DateField(default=datetime.datetime(2022, 7, 6, 9, 56, 38, 770333, tzinfo=utc), verbose_name='Премьера'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Кино'),
        ),
    ]
