# Generated by Django 3.2 on 2022-07-06 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_title_movie_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='dob',
        ),
    ]
